export default {
  apartments: [
    {
      id: 1,
      title: "Cozy Studio Apartment",
      type: "For Sale",
      price: "$1200/month",
      image: "/images/apartment1.jpg",
    },
    {
      id: 2,
      title: "Spacious Loft",
      type: "For Rent",
      price: "$2000/month",
      image: "/images/apartment2.jpg",
    },
    {
      id: 3,
      title: "Modern 1 Bedroom",
      type: "For Sale",
      price: "$1500/month",
      image: "/images/apartment3.jpg",
    },
    {
      id: 4,
      title: "Luxury 2 Bedroom",
      type: "For Rent",
      price: "$2500/month",
      image: "/images/apartment4.jpg",
    },
    {
      id: 5,
      title: "Cozy 2 Bedroom",
      type: "For Sale",
      price: "$1800/month",
      image: "/images/apartment5.jpg",
    },
    {
      id: 6,
      title: "Spacious 3 Bedroom",
      type: "For Rent",
      price: "$3000/month",
      image: "/images/apartment6.jpg",
    },
    {
      id: 7,
      title: "Modern Studio",
      type: "For Sale",
      price: "$1000/month",
      image: "/images/apartment7.jpg",
    },
    {
      id: 8,
      title: "Luxury 1 Bedroom",
      type: "For Rent",
      price: "$2200/month",
      image: "/images/apartment8.jpg",
    },
    {
      id: 9,
      title: "Cozy 3 Bedroom",
      type: "For Sale",
      price: "$2000/month",
      image: "/images/apartment9.jpg",
    },
    {
      id: 10,
      title: "Spacious 4 Bedroom",
      type: "For Rent",
      price: "$3500/month",
      image: "/images/apartment10.jpg",
    },
    {
      id: 11,
      title: "Modern 2 Bedroom",
      type: "For Sale",
      price: "$1600/month",
      image: "/images/apartment11.jpg",
    },
    {
      id: 12,
      title: "Luxury Studio",
      type: "For Rent",
      price: "$1800/month",
      image: "/images/apartment12.jpg",
    },
    {
      id: 13,
      title: "Cozy 1 Bedroom",
      type: "For Sale",
      price: "$1300/month",
      image: "/images/apartment13.jpg",
    },
    {
      id: 14,
      title: "Spacious 2 Bedroom",
      type: "For Rent",
      price: "$2800/month",
      image: "/images/apartment14.jpg",
    },
    {
      id: 15,
      title: "Modern 3 Bedroom",
      type: "For Sale",
      price: "$1900/month",
      image: "/images/apartment15.jpg",
    },
    {
      id: 16,
      title: "Luxury 3 Bedroom",
      type: "For Rent",
      price: "$3200/month",
      image: "/images/apartment16.jpg",
    },
    {
      id: 17,
      title: "Cozy Studio",
      type: "For Sale",
      price: "$1100/month",
      image: "/images/apartment17.jpg",
    },
    {
      id: 18,
      title: "Spacious 1 Bedroom",
      type: "For Rent",
      price: "$2400/month",
      image: "/images/apartment18.jpg",
    },
    {
      id: 19,
      title: "Modern 4 Bedroom",
      type: "For Sale",
      price: "$2100/month",
      image: "/images/apartment19.jpg",
    },
    {
      id: 20,
      title: "Luxury 4 Bedroom",
      type: "For Rent",
      price: "$3600/month",
      image: "/images/apartment20.jpg",
    },
    {
      id: 21,
      title: "Cozy 4 Bedroom",
      type: "For Sale",
      price: "$2300/month",
      image: "/images/apartment21.jpg",
    },
    {
      id: 22,
      title: "Spacious Loft",
      type: "For Rent",
      price: "$2900/month",
      image: "/images/apartment22.jpg",
    },
    {
      id: 23,
      title: "Modern Studio",
      type: "For Sale",
      price: "$1200/month",
      image: "/images/apartment23.jpg",
    },
    {
      id: 24,
      title: "Luxury 1 Bedroom",
      type: "For Rent",
      price: "$2600/month",
      image: "/images/apartment24.jpg",
    },
    {
      id: 25,
      title: "Cozy 2 Bedroom",
      type: "For Sale",
      price: "$1800/month",
      image: "/images/apartment25.jpg",
    },
    {
      id: 26,
      title: "Spacious 3 Bedroom",
      type: "For Rent",
      price: "$3100/month",
      image: "/images/apartment26.jpg",
    },
    {
      id: 27,
      title: "Modern 3 Bedroom",
      type: "For Sale",
      price: "$2000/month",
      image: "/images/apartment27.jpg",
    },
    {
      id: 28,
      title: "Luxury 2 Bedroom",
      type: "For Rent",
      price: "$2800/month",
      image: "/images/apartment28.jpg",
    },
    {
      id: 29,
      title: "Cozy Studio",
      type: "For Sale",
      price: "$1100/month",
      image: "/images/apartment29.jpg",
    },
    {
      id: 30,
      title: "Spacious 4 Bedroom",
      type: "For Rent",
      price: "$3400/month",
      image: "/images/apartment30.jpg",
    },
    {
      id: 31,
      title: "Test - Apartments",
      type: "Test",
      price: "Test",
      image: "/images/apartment30.jpg",
    },
  ],
  goods: [
    {
      id: 1,
      title: "Vintage Record Player",
      type: "Electronics",
      price: "$150",
      image: "/images/goods1.jpg",
    },
    {
      id: 2,
      title: "Mid-Century Coffee Table",
      type: "Furniture",
      price: "$300",
      image: "/images/goods2.jpg",
    },
    {
      id: 3,
      title: "Art Deco Vase",
      type: "Home Decor",
      price: "$200",
      image: "/images/goods3.jpg",
    },
    {
      id: 4,
      title: "Retro-Style Refrigerator",
      type: "Appliances",
      price: "$400",
      image: "/images/goods4.jpg",
    },
    {
      id: 5,
      title: "Vintage Typewriter",
      type: "Collectibles",
      price: "$100",
      image: "/images/goods5.jpg",
    },
    {
      id: 6,
      title: "Modern Sofa",
      type: "Furniture",
      price: "$500",
      image: "/images/goods6.jpg",
    },
    {
      id: 7,
      title: "Antique Clock",
      type: "Home Decor",
      price: "$250",
      image: "/images/goods7.jpg",
    },
    {
      id: 8,
      title: "Retro-Style Microwave",
      type: "Appliances",
      price: "$300",
      image: "/images/goods8.jpg",
    },
    {
      id: 9,
      title: "Vintage Camera",
      type: "Electronics",
      price: "$200",
      image: "/images/goods9.jpg",
    },
    {
      id: 10,
      title: "Mid-Century Armchair",
      type: "Furniture",
      price: "$350",
      image: "/images/goods10.jpg",
    },
    {
      id: 11,
      title: "Vintage Watch",
      type: "Jewelry",
      price: "$150",
      image: "/images/goods11.jpg",
    },
    {
      id: 12,
      title: "Retro-Style Radio",
      type: "Electronics",
      price: "$250",
      image: "/images/goods12.jpg",
    },
    {
      id: 13,
      title: "Antique Bookshelf",
      type: "Furniture",
      price: "$400",
      image: "/images/goods13.jpg",
    },
    {
      id: 14,
      title: "Vintage Handbag",
      type: "Fashion",
      price: "$200",
      image: "/images/goods14.jpg",
    },
    {
      id: 15,
      title: "Mid-Century Desk",
      type: "Furniture",
      price: "$350",
      image: "/images/goods15.jpg",
    },
    {
      id: 16,
      title: "Retro-Style Phone",
      type: "Electronics",
      price: "$150",
      image: "/images/goods16.jpg",
    },
    {
      id: 17,
      title: "Vintage Poster",
      type: "Art",
      price: "$100",
      image: "/images/goods17.jpg",
    },
    {
      id: 18,
      title: "Antique Vase",
      type: "Home Decor",
      price: "$250",
      image: "/images/goods18.jpg",
    },
    {
      id: 19,
      title: "Mid-Century Chair",
      type: "Furniture",
      price: "$300",
      image: "/images/goods19.jpg",
    },
    {
      id: 20,
      title: "Vintage Camera Lens",
      type: "Electronics",
      price: "$200",
      image: "/images/goods20.jpg",
    },
    {
      id: 21,
      title: "Vintage Bicycle",
      type: "Requests21",
      price: "$200",
      image: "/images/requests21.jpg",
    },
    {
      id: 22,
      title: "Mid-Century Lamp",
      type: "Requests22",
      price: "$150",
      image: "/images/requests22.jpg",
    },
    {
      id: 23,
      title: "Antique Clock",
      type: "Requests23",
      price: "$300",
      image: "/images/requests23.jpg",
    },
    {
      id: 24,
      title: "Retro-Style Radio",
      type: "Requests24",
      price: "$250",
      image: "/images/requests24.jpg",
    },
    {
      id: 25,
      title: "Vintage Camera",
      type: "Requests25",
      price: "$200",
      image: "/images/requests25.jpg",
    },
    {
      id: 26,
      title: "Mid-Century Armchair",
      type: "Requests26",
      price: "$350",
      image: "/images/requests26.jpg",
    },
    {
      id: 27,
      title: "Antique Bookshelf",
      type: "Requests27",
      price: "$400",
      image: "/images/requests27.jpg",
    },
    {
      id: 28,
      title: "Vintage Watch",
      type: "Requests28",
      price: "$150",
      image: "/images/requests28.jpg",
    },
    {
      id: 29,
      title: "Retro-Style Phone",
      type: "Requests29",
      price: "$100",
      image: "/images/requests29.jpg",
    },
    {
      id: 30,
      title: "Vintage Poster",
      type: "Requests30",
      price: "$50",
      image: "/images/requests30.jpg",
    },
    {
      id: 31,
      title: "Test - Goods",
      type: "Test",
      price: "Test",
      image: "/images/requests30.jpg",
    },
  ],
  services: [
    {
      id: 1,
      title: "Web Development",
      type: "Services1",
      price: "$50/hour",
      image: "/images/services1.jpg",
    },
    {
      id: 2,
      title: "Graphic Design",
      type: "Services2",
      price: "$40/hour",
      image: "/images/services2.jpg",
    },
    {
      id: 3,
      title: "Digital Marketing",
      type: "Services3",
      price: "$60/hour",
      image: "/images/services3.jpg",
    },
    {
      id: 4,
      title: "Photography",
      type: "Services4",
      price: "$100/hour",
      image: "/images/services4.jpg",
    },
    {
      id: 5,
      title: "Video Production",
      type: "Services5",
      price: "$150/hour",
      image: "/images/services5.jpg",
    },
    {
      id: 6,
      title: "Writing and Editing",
      type: "Services6",
      price: "$30/hour",
      image: "/images/services6.jpg",
    },
    {
      id: 7,
      title: "Social Media Management",
      type: "Services7",
      price: "$50/hour",
      image: "/images/services7.jpg",
    },
    {
      id: 8,
      title: "Event Planning",
      type: "Services8",
      price: "$75/hour",
      image: "/images/services8.jpg",
    },
    {
      id: 9,
      title: "Interior Design",
      type: "Services9",
      price: "$80/hour",
      image: "/images/services9.jpg",
    },
    {
      id: 10,
      title: "Landscape Design",
      type: "Services10",
      price: "$90/hour",
      image: "/images/services10.jpg",
    },
    {
      id: 11,
      title: "Translation Services",
      type: "Services11",
      price: "$40/hour",
      image: "/images/services11.jpg",
    },
    {
      id: 12,
      title: "Virtual Assistant",
      type: "Services12",
      price: "$30/hour",
      image: "/images/services12.jpg",
    },
    {
      id: 13,
      title: "Social Media Advertising",
      type: "Services13",
      price: "$60/hour",
      image: "/images/services13.jpg",
    },
    {
      id: 14,
      title: "Web Design",
      type: "Services14",
      price: "$80/hour",
      image: "/images/services14.jpg",
    },
    {
      id: 15,
      title: "Content Writing",
      type: "Services15",
      price: "$50/hour",
      image: "/images/services15.jpg",
    },
    {
      id: 16,
      title: "Video Editing",
      type: "Services16",
      price: "$70/hour",
      image: "/images/services16.jpg",
    },
    {
      id: 17,
      title: "Graphic Design",
      type: "Services17",
      price: "$45/hour",
      image: "/images/services17.jpg",
    },
    {
      id: 18,
      title: "SEO Optimization",
      type: "Services18",
      price: "$55/hour",
      image: "/images/services18.jpg",
    },
    {
      id: 19,
      title: "Email Marketing",
      type: "Services19",
      price: "$65/hour",
      image: "/images/services19.jpg",
    },
    {
      id: 20,
      title: "Online Research",
      type: "Services20",
      price: "$35/hour",
      image: "/images/services20.jpg",
    },
    {
      id: 21,
      title: "Podcast Editing",
      type: "Services21",
      price: "$60/hour",
      image: "/images/services21.jpg",
    },
    {
      id: 22,
      title: "Social Media Management",
      type: "Services22",
      price: "$50/hour",
      image: "/images/services22.jpg",
    },
    {
      id: 23,
      title: "Web Development",
      type: "Services23",
      price: "$80/hour",
      image: "/images/services23.jpg",
    },
    {
      id: 24,
      title: "Content Creation",
      type: "Services24",
      price: "$55/hour",
      image: "/images/services24.jpg",
    },
    {
      id: 25,
      title: "Video Production",
      type: "Services25",
      price: "$70/hour",
      image: "/images/services25.jpg",
    },
    {
      id: 26,
      title: "Graphic Design",
      type: "Services26",
      price: "$45/hour",
      image: "/images/services26.jpg",
    },
    {
      id: 27,
      title: "Digital Marketing",
      type: "Services27",
      price: "$65/hour",
      image: "/images/services27.jpg",
    },
    {
      id: 28,
      title: "Email Marketing",
      type: "Services28",
      price: "$60/hour",
      image: "/images/services28.jpg",
    },
    {
      id: 29,
      title: "Online Research",
      type: "Services29",
      price: "$35/hour",
      image: "/images/services29.jpg",
    },
    {
      id: 30,
      title: "Data Analysis",
      type: "Services30",
      price: "$75/hour",
      image: "/images/services30.jpg",
    },
    {
      id: 31,
      title: "Test - Services",
      type: "Test",
      price: "Test",
      image: "/images/services30.jpg",
    },
  ],
  requests: [
    {
      id: 1,
      title: "Vintage Record Player",
      type: "Requests1",
      price: "$150",
      image: "/images/requests1.jpg",
    },
    {
      id: 2,
      title: "Mid-Century Coffee Table",
      type: "Requests2",
      price: "$300",
      image: "/images/requests2.jpg",
    },
    {
      id: 3,
      title: "Art Deco Vase",
      type: "Requests3",
      price: "$200",
      image: "/images/requests3.jpg",
    },
    {
      id: 4,
      title: "Retro- Style Refrigerator",
      type: "Requests4",
      price: "$400",
      image: "/images/requests4.jpg",
    },
    {
      id: 5,
      title: "Vintage Typewriter",
      type: "Requests5",
      price: "$100",
      image: "/images/requests5.jpg",
    },
    {
      id: 6,
      title: "Modern Sofa",
      type: "Requests6",
      price: "$500",
      image: "/images/requests6.jpg",
    },
    {
      id: 7,
      title: "Antique Clock",
      type: "Requests7",
      price: "$250",
      image: "/images/requests7.jpg",
    },
    {
      id: 8,
      title: "Retro-Style Microwave",
      type: "Requests8",
      price: "$300",
      image: "/images/requests8.jpg",
    },
    {
      id: 9,
      title: "Vintage Camera",
      type: "Requests9",
      price: "$200",
      image: "/images/requests9.jpg",
    },
    {
      id: 10,
      title: "Mid-Century Armchair",
      type: "Requests10",
      price: "$350",
      image: "/images/requests10.jpg",
    },
    {
      id: 11,
      title: "Vintage Watch",
      type: "Requests11",
      price: "$150",
      image: "/images/requests11.jpg",
    },
    {
      id: 12,
      title: "Retro-Style Radio",
      type: "Requests12",
      price: "$250",
      image: "/images/requests12.jpg",
    },
    {
      id: 13,
      title: "Antique Bookshelf",
      type: "Requests13",
      price: "$400",
      image: "/images/requests13.jpg",
    },
    {
      id: 14,
      title: "Vintage Handbag",
      type: "Requests14",
      price: "$200",
      image: "/images/requests14.jpg",
    },
    {
      id: 15,
      title: "Mid-Century Desk",
      type: "Requests15",
      price: "$350",
      image: "/images/requests15.jpg",
    },
    {
      id: 16,
      title: "Retro-Style Phone",
      type: "Requests16",
      price: "$150",
      image: "/images/requests16.jpg",
    },
    {
      id: 17,
      title: "Vintage Poster",
      type: "Requests17",
      price: "$100",
      image: "/images/requests17.jpg",
    },
    {
      id: 18,
      title: "Antique Vase",
      type: "Requests18",
      price: "$250",
      image: "/images/requests18.jpg",
    },
    {
      id: 19,
      title: "Mid-Century Chair",
      type: "Requests19",
      price: "$300",
      image: "/images/requests19.jpg",
    },
    {
      id: 20,
      title: "Vintage Camera Lens",
      type: "Requests20",
      price: "$200",
      image: "/images/requests20.jpg",
    },
    {
      id: 21,
      title: "Vintage Bicycle",
      type: "Requests21",
      price: "$200",
      image: "/images/requests21.jpg",
    },
    {
      id: 22,
      title: "Mid-Century Lamp",
      type: "Requests22",
      price: "$150",
      image: "/images/requests22.jpg",
    },
    {
      id: 23,
      title: "Antique Clock",
      type: "Requests23",
      price: "$300",
      image: "/images/requests23.jpg",
    },
    {
      id: 24,
      title: "Retro-Style Radio",
      type: "Requests24",
      price: "$250",
      image: "/images/requests24.jpg",
    },
    {
      id: 25,
      title: "Vintage Camera",
      type: "Requests25",
      price: "$200",
      image: "/images/requests25.jpg",
    },
    {
      id: 26,
      title: "Mid-Century Armchair",
      type: "Requests26",
      price: "$350",
      image: "/images/requests26.jpg",
    },
    {
      id: 27,
      title: "Antique Bookshelf",
      type: "Requests27",
      price: "$400",
      image: "/images/requests27.jpg",
    },
    {
      id: 28,
      title: "Vintage Watch",
      type: "Requests28",
      price: "$150",
      image: "/images/requests28.jpg",
    },
    {
      id: 29,
      title: "Retro-Style Phone",
      type: "Requests29",
      price: "$100",
      image: "/images/requests29.jpg",
    },
    {
      id: 30,
      title: "Vintage Poster",
      type: "Requests30",
      price: "$50",
      image: "/images/requests30.jpg",
    },
    {
      id: 31,
      title: "Test - Requests",
      type: "Test",
      price: "Test",
      image: "/images/requests30.jpg",
    },
  ],
};
